# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.31)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS aja::ntv2)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target aja::ntv2
add_library(aja::ntv2 STATIC IMPORTED)

set_target_properties(aja::ntv2 PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/vol/apps/aja-ntv2-sdk/17.1.3/includes/libajantv2/ajantv2/includes"
)

if(NOT CMAKE_VERSION VERSION_LESS "3.23.0")
  file(GLOB
    _AJA_HEADERS
    "/vol/apps/aja-ntv2-sdk/17.1.3/includes/libajantv2/ajantv2/includes/*.h"
  )
  target_sources(aja::ntv2
    INTERFACE
      FILE_SET "HEADERS"
      TYPE "HEADERS"
      BASE_DIRS
        "/vol/apps/aja-ntv2-sdk/17.1.3/includes/libajantv2"
        "/vol/apps/aja-ntv2-sdk/17.1.3/includes/libajantv2/ajabase"
        "/vol/apps/aja-ntv2-sdk/17.1.3/includes/libajantv2/ajantv2/includes"
        "/vol/apps/aja-ntv2-sdk/17.1.3/includes/libajantv2/ajantv2/src/lin"
      FILES ${_AJA_HEADERS}
  )
  unset(_AJA_HEADERS)
else()
  set_property(TARGET aja::ntv2
    APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES
      "/vol/apps/aja-ntv2-sdk/17.1.3/includes/libajantv2"
      "/vol/apps/aja-ntv2-sdk/17.1.3/includes/libajantv2/ajabase"
      "/vol/apps/aja-ntv2-sdk/17.1.3/includes/libajantv2/ajantv2/includes"
      "/vol/apps/aja-ntv2-sdk/17.1.3/includes/libajantv2/ajantv2/src/lin"
  )
endif()

# Import target "aja::ntv2" for configuration ""
set_property(TARGET aja::ntv2 APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(aja::ntv2 PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_NOCONFIG "CXX"
  IMPORTED_LOCATION_NOCONFIG "/vol/apps/aja-ntv2-sdk/17.1.3/lib/libajantv2.a"
  )

# Configure aja to use linux headers
target_compile_definitions(aja::ntv2 INTERFACE AJALinux=1)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
